### ISSUE TITLE
kotlin冲突了，怎么排除内部依赖的kotlin-stdlib这个依赖

### ISSUE THREAD

**Issue by 2993277254** [kongzue/BaseOkHttpV3#15]
因为使用了别的版本的kotlin依赖，作者大大想过这个问题吗

**Comment by kongzue** [comment]
主要问题在于okHttp底层的关系，实际上BaseOkHttpV3是Java开发的二次封装，而最新版本的okHttp需要kotlin，这里是为了方便引入所以直接将okhttp的依赖全部集成进来了，如遇到kotlin版本冲突，建议单独引入okHttp，然后下拉BaseOkHttpV3的源码进行引入，只需要包含如下地址的代码即可：
```
https://github.com/kongzue/BaseOkHttpV3/tree/master/baseokhttp_v3/src/main/java/com/kongzue/baseokhttp
```

**Comment by kongzue** [comment]
请尝试 jitpack 最新版本，具体请查看 README.md。
