### ISSUE TITLE
你好，选择了某些文件后点击上传按钮就没反应

### ISSUE THREAD

**Issue by 861619009** [kongzue/BaseOkHttpV3#19]
比如后缀为iApp的(test.iApp)，选择这个文件后上传没反应，改为zip就可以上传(不是后端接口的问题)

**Comment by kongzue** [comment]
此文件格式非标准文件格式

________________________________
发件人: 861619009 ***@***.***>
发送时间: Wednesday, October 20, 2021 9:26:28 PM
收件人: kongzue/BaseOkHttpV3 ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kongzue/BaseOkHttpV3] 你好，选择了某些文件后点击上传按钮就没反应 (Issue #19)


比如后缀为iApp的(test.iApp)，选择这个文件后上传没反应，改为zip就可以上传(不是后端接口的问题)

―
