### ISSUE TITLE
则么处理接口404和500

### ISSUE THREAD

**Issue by 1432886945** [kongzue/BaseOkHttpV3#2]

**Comment by kongzue** [comment]
如果返回error不为null则接口错误，具体错误请根据error类型判断


<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=myzcxhh&uid=myzcxhh%40live.cn&iconUrl=http%3A%2F%2Fmail-online.nosdn.127.net%2F58110a727ef45bedcdc890795902a8d2.jpg&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Amyzcxhh%40live.cn%22%5D>
[http://mail-online.nosdn.127.net/58110a727ef45bedcdc890795902a8d2.jpg]
myzcxhh

邮箱：myzcxhh@live.cn


Signature is customized by Netease Mail Master<https://mail.163.com/dashi/dlpro.html?from=mail88>

在2019年01月25日 14:05，1432886945<mailto:notifications@github.com> 写道：

**Comment by 1432886945** [comment]
这是我对你的网络做的封装


import android.app.Activity
import baseokhttp3.MediaType
import com.google.gson.Gson
import com.hisan.base.network.model.DataModel
import com.hisan.base.network.model.callBack.DataCallBack
import com.hisan.base.network.model.callBack.ErrorCallBack
import com.hisan.base.ui.BaseApplication
import com.hisan.base.utils.EasyLog
import com.hisan.base.utils.SPUtils
import com.hisan.base.utils.gson.gsonUtils
import com.hjq.toast.ToastUtils
import com.kongzue.baseokhttp.HttpRequest
import com.kongzue.baseokhttp.exceptions.TimeOutException
import com.kongzue.baseokhttp.util.BaseOkHttp
import com.kongzue.baseokhttp.util.HttpParams
import org.greenrobot.eventbus.EventBus
import org.jsoup.Jsoup
import java.io.IOException

/**
 * 自定义网络请求库
 */
class OkHttpUtils {

    //单利
    companion object {
        val instance by lazy(LazyThreadSafetyMode.SYNCHRONIZED) {
            OkHttpUtils()
        }
    }

    /**
     *
     * @param url 链接
     * @param httpParams 请求参数
     * @param request 请求方式 BaseOkHttp.GET_REQUEST、BaseOkHttp.POST_REQUEST、BaseOkHttp.PUT_REQUEST、BaseOkHttp.DELETE_REQUEST
     * @param isShow 是否显示加载loading
     * @param dataCallBack 请求成功回调
     * @param errorCallBack 请求失败回调，默认不重写，使用默认的错误弹窗
     */
    fun getData(activity: Activity, url: String, dataCallBack: DataCallBack, parameter: HttpParams? = null, request: Int? = BaseOkHttp.GET_REQUEST, isShow: Boolean? = false, errorCallBack: ErrorCallBack? = null) {
        if (isShow!!) diaLogUtils.instance.showDialog(activity)
        val token = SPUtils.getInstance().getString("token")
        token?.takeIf { token != "" }.apply {
            BaseOkHttp.overallHeader = HttpParams()
                    .add("token", token)
        }
        parameter?.let {
            if (parameter.keys.contains("page") && !parameter.keys.contains("size")) parameter.add("size", 50)
            if (!parameter.keys.contains("lon")) {
                BaseApplication.lat?.let {
                    parameter.add("latitude", BaseApplication.lat!!)
                }
            }
            if (!parameter.keys.contains("lon")) {
                BaseApplication.log?.let {
                    parameter.add("longitude", BaseApplication.log!!)
                }
            }
            BaseApplication.city_id?.let {
                if (!parameter.keys.contains("city_id")) parameter.add("city_id", BaseApplication.city_id)
            }
        }
        HttpRequest.build(activity, url)
                .setParameter(parameter)
                .setMediaType(MediaType.parse("application/jpg"))
                .setResponseListener { response, error ->
                    returnData(response, error, dataCallBack, errorCallBack)
                }.doRequest(request!!)
    }
}

//返回数据
private fun returnData(response: String?, e: Exception?, dataCallBack: DataCallBack?, errorCallBack: ErrorCallBack?) {
    diaLogUtils.instance.dismissDialog()
    if (response != null) {
        if (JsonUtils.isBadJson(response)) {
            EasyLog.DEFAULT.v(response)
            val model = gsonUtils.gsonToBean(response, DataModel::class.java)
            if (dataIsNull(model)) {
                dataCallBack?.onSuccessData(gsonUtils.gsonString(model?.data))
            } else {
                if (errorCallBack == null) {
                    showToast(model?.msg)
                } else {
                    errorCallBack.onErrorCode(model?.error_code, model?.msg)
                }
            }
        } else {
            dataCallBack?.onSuccessData(null)
            //解析接口错误返回的html
            val doc = Jsoup.parse(response)
            //获取字符串的数据
            when (JsonUtils.extractStr(doc.title())) {
                404 -> {
                    showToast("接口地址不存在")
                }
                500 -> {
                    showToast("api地址异常")
                    val doc = Jsoup.parse(response)
                    val elements = doc.select("div.exception")
                    EasyLog.DEFAULT.v(elements)
                }
                else -> {
                    EasyLog.DEFAULT.v(JsonUtils.extractStr(doc.title()))
                }
            }
        }
    }
    if (e != null) {
        when (e) {
            //请求超时
            is TimeOutException -> {
                showToast("请求超时")
                dataCallBack?.onSuccessData(null)
            }
            //数据异常
            is IOException -> {
                EasyLog.DEFAULT.v("数据异常")
                dataCallBack?.onSuccessData(null)
            }
            //未知异常
            else -> {
                EasyLog.DEFAULT.v("未知异常:" + e.toString())
            }
        }
    }

}

/**
 * 判断返回数据是否正确
 */
private fun dataIsNull(data: DataModel?): Boolean {
    val errorCode = data?.error_code
    if (errorCode != 0) {
        when (errorCode) {
            10000 -> EasyLog.DEFAULT.v("数据请求验证失败")
            10001 -> EasyLog.DEFAULT.v("无效的参数")
            10002 -> EasyLog.DEFAULT.v("请求参数无效,请重新输入")
            10003 -> EasyLog.DEFAULT.v("请求参数不存在")
            20001 -> showToast("登录失败，请稍后再试")
            20002 -> showToast("登录失败,请检查用户名和密码")
            20003 -> showToast("登录失败，账户异常，请联系管理员")
            20004 -> EasyLog.DEFAULT.v("等待扫描登录")
            20005 -> EasyLog.DEFAULT.v("AUTH登录类型错误")
            20006 -> showToast("当前账号未注册")
            20007 -> showToast("分享码错误")
            20008 -> showToast("账号已存在")
            20009 -> showToast("注册失败")
            20010 -> showToast("请先绑定手机号")
            40001 -> EventBus.getDefault().post("当前用户已退出,请重新登入")
            40002 -> {
                EasyLog.DEFAULT.v("服务器缓存异常,一般为登录")
                showToast("服务器异常,请稍后再试")
            }
            40004 -> {
                EasyLog.DEFAULT.v("客户ip进入黑名单")
                showToast("账号异常无法使用,请联系管理员")
            }
            40005, 40006 -> showToast("当前用户无操作权限")
            50001 -> showToast("文件内容不能为空")
            50002 -> showToast("上传出错了")
            60001 -> {
                showToast("当前店铺被删除，无法访问")
            }
            61001 -> {
                showToast("当前商品被删除，无法访问")
            }
            90001 -> {
                EasyLog.DEFAULT.v("数据已存在")
                showToast("当前数据已存在,请勿重复添加")
            }
            90002 -> {
                EasyLog.DEFAULT.v("缺乏参数,操作失败")
            }
            90003 -> {
                showToast("定位失败")
            }
        }
        return false
    }
    return true
}

private fun showToast(msg: String?) {
    ToastUtils.show(msg)
}

**Comment by kongzue** [comment]
很感谢，BaseOkHttp的主旨就在于简化很多处理操作以达到更高效的开发，可能对一些细节处理并不完善，我也会继续维护并完善它的功能和设计。另外您可以Fork一个分支到您的Github作出修改。

**Comment by 1432886945** [comment]
好的,我有空的话会把我修改的代码发上去,最好你能出套kotlin的,因为我都是用kotlin写的

**Comment by kongzue** [comment]
这个实在是抱歉，因为目前我手头项目实在太多以至于暂时未能接触kotlin的开发，目前只能用Java实现，不会有空我会学习kotlin的，感谢你的建议

**Comment by 1432886945** [comment]
嗯好的

**Comment by 1432886945** [comment]
你qq号多少?.我把我封装的demo发你,你看看,行的话,发布到你现在的demo上吧,懒得建项目了
