### ISSUE TITLE
HttpRequest url为null的逻辑判断有点问题

### ISSUE THREAD

**Issue by kong6001** [kongzue/BaseOkHttpV3#4]
if (!url.startsWith("http")) { //如果url为null,这里就有问题，后面的isNull没起到该起的作用
                url = serviceUrl + url;
            }
            if (isNull(url)) {
                Log.e(">>>", "-------------------------------------");
                Log.e(">>>", "创建请求失败: 请求地址不能为空");
                Log.e(">>>", "=====================================");
            }

**Comment by kongzue** [comment]
感谢提醒，写的比较急没注意，会在下一版本修复
