### ISSUE TITLE
本人小白，不太懂如何解析response,希望大神能教一下。

### ISSUE THREAD

**Issue by xiaobai567** [kongzue/BaseOkHttpV3#5]

**Comment by xiaobai567** [comment]
就好像“一般请求”那里有个可以直接解析到msg的value：resultHttp.setText(main.getString("msg"));那我想解析data里面的femalename的值应该怎么处理呢？

**Comment by kongzue** [comment]
如果data是个jsonObject：
main.getJsonMap("data").getString("femalename")
如果是jsonArray:
main.getList("data").getJsonMap(0).getString("femalename")
